export type World = {
  id: string;
  name: string;
  emoji: string;
  color: string;
  secondaryColor: string;
  accentColor: string;
  difficulty: string;
  cefrLevel: string;
  narrative: string;
  description: string;
  order: number;
};

export type MissionDynamic = 
  | "Quiz Master"
  | "Puzzle Solver"
  | "Simulation Quest"
  | "Memory Challenge"
  | "Dialogue Battle"
  | "Listening Expedition"
  | "Writing Fortress"
  | "Pronunciation Duel"
  | "Logic Labyrinth"
  | "Boss Battle";

export type Mission = {
  id: string;
  worldId: string;
  name: string;
  objective: string;
  dynamic: MissionDynamic;
  difficulty: number; // 1-6 stars
  order: number;
  xpReward: number;
};

export const WORLDS: World[] = [
  {
    id: "foundation-realm",
    name: "The Foundation Realm",
    emoji: "🏰",
    color: "#4A90E2",
    secondaryColor: "#87CEEB",
    accentColor: "#FFD700",
    difficulty: "Beginner",
    cefrLevel: "A1",
    narrative: "You are an apprentice who has just arrived at the Foundation Realm. Here you will learn the basic spells of the English language: greetings, personal identity, and the first building blocks of grammar.",
    description: "Master the fundamentals of English in this welcoming castle where every adventurer begins their journey.",
    order: 1,
  },
  {
    id: "action-arena",
    name: "The Action Arena",
    emoji: "⚔️",
    color: "#FF9500",
    secondaryColor: "#E74C3C",
    accentColor: "#FFC107",
    difficulty: "Elementary",
    cefrLevel: "A2",
    narrative: "You advance to the Action Arena, where you will master verbs and learn to tell stories of the past. Warriors here speak about what they do, did, and will do.",
    description: "Battle through verb tenses and conquer the past, present, and future in this dynamic arena.",
    order: 2,
  },
  {
    id: "experience-citadel",
    name: "The Experience Citadel",
    emoji: "🏛️",
    color: "#50C878",
    secondaryColor: "#808000",
    accentColor: "#DAA520",
    difficulty: "Intermediate",
    cefrLevel: "B1",
    narrative: "You arrive at the Experience Citadel, where adventurers share their life stories. Here you will master the Present Perfect, the heart of B1, and learn to connect past and present.",
    description: "Share your experiences and connect time periods in this ancient citadel of knowledge.",
    order: 3,
  },
  {
    id: "mastery-kingdom",
    name: "The Mastery Kingdom",
    emoji: "👑",
    color: "#9B59B6",
    secondaryColor: "#E6B0FF",
    accentColor: "#C0C0C0",
    difficulty: "Upper-Intermediate",
    cefrLevel: "B2",
    narrative: "You enter the Mastery Kingdom, where advanced speakers master the Passive Voice and complex conditionals. Here linguistic precision and sophistication are forged.",
    description: "Rule over complex grammar structures and sophisticated expressions in this royal palace.",
    order: 4,
  },
  {
    id: "eloquence-observatory",
    name: "The Eloquence Observatory",
    emoji: "🔭",
    color: "#4B0082",
    secondaryColor: "#000080",
    accentColor: "#C0C0C0",
    difficulty: "Advanced",
    cefrLevel: "C1",
    narrative: "You ascend to the Eloquence Observatory, where language masters use advanced rhetorical structures. Here you will master inversion, cleft sentences, and linguistic emphasis.",
    description: "Observe the stars of eloquence and master the art of rhetorical expression.",
    order: 5,
  },
  {
    id: "perfection-sanctum",
    name: "The Perfection Sanctum",
    emoji: "💎",
    color: "#C0C0C0",
    secondaryColor: "#FFFFFF",
    accentColor: "#B9F2FF",
    difficulty: "Mastery",
    cefrLevel: "C2",
    narrative: "You reach the Perfection Sanctum, where language transcends rules to become art. Here you will master nuance, irony, and complete register mastery.",
    description: "Achieve linguistic perfection in this sacred temple where language becomes an art form.",
    order: 6,
  },
  {
    id: "pronunciation-theater",
    name: "The Pronunciation Theater",
    emoji: "🎤",
    color: "#E74C3C",
    secondaryColor: "#DC143C",
    accentColor: "#FFD700",
    difficulty: "Transversal",
    cefrLevel: "A1-C2",
    narrative: "The Pronunciation Theater is a special stage where you perfect your voice at every level. Here language actors learn to sound like natives, from individual phonemes to complex intonation.",
    description: "Perform on the grand stage and perfect your pronunciation from beginner to native-like fluency.",
    order: 7,
  },
  {
    id: "competence-nexus",
    name: "The Competence Nexus",
    emoji: "🌐",
    color: "#FFD700",
    secondaryColor: "#FFA500",
    accentColor: "#FF6347",
    difficulty: "Transversal",
    cefrLevel: "A1-C2",
    narrative: "The Competence Nexus is the heart of your journey, where you integrate everything learned. Here all worlds intersect: grammar, vocabulary, pronunciation, and real communication skills.",
    description: "Unite all your skills in this futuristic nexus where true competence is demonstrated.",
    order: 8,
  },
];

export const MISSIONS: Mission[] = [
  // Foundation Realm (A1) - 10 missions
  {
    id: "foundation-1",
    worldId: "foundation-realm",
    name: "Greetings Quest",
    objective: "Master basic greetings and introductions",
    dynamic: "Quiz Master",
    difficulty: 1,
    order: 1,
    xpReward: 50,
  },
  {
    id: "foundation-2",
    worldId: "foundation-realm",
    name: "Name Your Identity",
    objective: "Learn personal pronouns and 'to be'",
    dynamic: "Puzzle Solver",
    difficulty: 1,
    order: 2,
    xpReward: 50,
  },
  {
    id: "foundation-3",
    worldId: "foundation-realm",
    name: "Color Spectrum Challenge",
    objective: "Identify and name colors",
    dynamic: "Memory Challenge",
    difficulty: 1,
    order: 3,
    xpReward: 50,
  },
  {
    id: "foundation-4",
    worldId: "foundation-realm",
    name: "Number Nexus",
    objective: "Count from 1-100 and understand quantities",
    dynamic: "Logic Labyrinth",
    difficulty: 1,
    order: 4,
    xpReward: 50,
  },
  {
    id: "foundation-5",
    worldId: "foundation-realm",
    name: "Days & Time Keeper",
    objective: "Master days, months, and basic time",
    dynamic: "Simulation Quest",
    difficulty: 1,
    order: 5,
    xpReward: 50,
  },
  {
    id: "foundation-6",
    worldId: "foundation-realm",
    name: "Phoneme Fortress",
    objective: "Practice individual phonemes (/p/, /b/, /t/, /d/)",
    dynamic: "Pronunciation Duel",
    difficulty: 1,
    order: 6,
    xpReward: 75,
  },
  {
    id: "foundation-7",
    worldId: "foundation-realm",
    name: "Classroom Commands",
    objective: "Learn basic classroom vocabulary and imperatives",
    dynamic: "Dialogue Battle",
    difficulty: 1,
    order: 7,
    xpReward: 50,
  },
  {
    id: "foundation-8",
    worldId: "foundation-realm",
    name: "Family Tree Builder",
    objective: "Introduce family members and relationships",
    dynamic: "Writing Fortress",
    difficulty: 1,
    order: 8,
    xpReward: 50,
  },
  {
    id: "foundation-9",
    worldId: "foundation-realm",
    name: "Listening Lighthouse",
    objective: "Understand basic spoken English",
    dynamic: "Listening Expedition",
    difficulty: 1,
    order: 9,
    xpReward: 75,
  },
  {
    id: "foundation-10",
    worldId: "foundation-realm",
    name: "Guardian of Foundations",
    objective: "BOSS BATTLE - Comprehensive A1 Assessment",
    dynamic: "Boss Battle",
    difficulty: 1,
    order: 10,
    xpReward: 200,
  },

  // Action Arena (A2) - 10 missions
  {
    id: "action-1",
    worldId: "action-arena",
    name: "Verb Vault",
    objective: "Master present simple with action verbs",
    dynamic: "Quiz Master",
    difficulty: 2,
    order: 1,
    xpReward: 75,
  },
  {
    id: "action-2",
    worldId: "action-arena",
    name: "Past Tense Portal",
    objective: "Learn regular past simple verbs",
    dynamic: "Puzzle Solver",
    difficulty: 2,
    order: 2,
    xpReward: 75,
  },
  {
    id: "action-3",
    worldId: "action-arena",
    name: "Irregular Warriors",
    objective: "Conquer irregular past simple verbs",
    dynamic: "Memory Challenge",
    difficulty: 2,
    order: 3,
    xpReward: 75,
  },
  {
    id: "action-4",
    worldId: "action-arena",
    name: "Future Forecast",
    objective: "Predict the future with 'will' and 'going to'",
    dynamic: "Logic Labyrinth",
    difficulty: 2,
    order: 4,
    xpReward: 75,
  },
  {
    id: "action-5",
    worldId: "action-arena",
    name: "Pronunciation Patrol",
    objective: "Master '-ed' ending pronunciation (/t/, /d/, /ɪd/)",
    dynamic: "Pronunciation Duel",
    difficulty: 2,
    order: 5,
    xpReward: 100,
  },
  {
    id: "action-6",
    worldId: "action-arena",
    name: "Story Spinner",
    objective: "Narrate past events in connected sequences",
    dynamic: "Writing Fortress",
    difficulty: 2,
    order: 6,
    xpReward: 75,
  },
  {
    id: "action-7",
    worldId: "action-arena",
    name: "Dialogue Duel",
    objective: "Engage in past/present conversations",
    dynamic: "Dialogue Battle",
    difficulty: 2,
    order: 7,
    xpReward: 75,
  },
  {
    id: "action-8",
    worldId: "action-arena",
    name: "Listening Labyrinth",
    objective: "Comprehend stories in past tense",
    dynamic: "Listening Expedition",
    difficulty: 2,
    order: 8,
    xpReward: 100,
  },
  {
    id: "action-9",
    worldId: "action-arena",
    name: "Transfer Trap",
    objective: "Avoid hispanophone-specific errors",
    dynamic: "Simulation Quest",
    difficulty: 2,
    order: 9,
    xpReward: 75,
  },
  {
    id: "action-10",
    worldId: "action-arena",
    name: "Warlord of Actions",
    objective: "BOSS BATTLE - A2 Mastery Challenge",
    dynamic: "Boss Battle",
    difficulty: 2,
    order: 10,
    xpReward: 300,
  },

  // Experience Citadel (B1) - 10 missions
  {
    id: "experience-1",
    worldId: "experience-citadel",
    name: "Perfect Present",
    objective: "Understand Present Perfect formation",
    dynamic: "Quiz Master",
    difficulty: 3,
    order: 1,
    xpReward: 100,
  },
  {
    id: "experience-2",
    worldId: "experience-citadel",
    name: "Experience Explorer",
    objective: "Use Present Perfect for life experiences",
    dynamic: "Simulation Quest",
    difficulty: 3,
    order: 2,
    xpReward: 100,
  },
  {
    id: "experience-3",
    worldId: "experience-citadel",
    name: "Relative Clause Realm",
    objective: "Master defining relative clauses",
    dynamic: "Puzzle Solver",
    difficulty: 3,
    order: 3,
    xpReward: 100,
  },
  {
    id: "experience-4",
    worldId: "experience-citadel",
    name: "Comparison Crown",
    objective: "Use comparatives and superlatives effectively",
    dynamic: "Logic Labyrinth",
    difficulty: 3,
    order: 4,
    xpReward: 100,
  },
  {
    id: "experience-5",
    worldId: "experience-citadel",
    name: "Rhythm Revealer",
    objective: "Master stress-timed rhythm and schwa (/ə/)",
    dynamic: "Pronunciation Duel",
    difficulty: 3,
    order: 5,
    xpReward: 125,
  },
  {
    id: "experience-6",
    worldId: "experience-citadel",
    name: "Narrative Nexus",
    objective: "Write complex narratives with mixed tenses",
    dynamic: "Writing Fortress",
    difficulty: 3,
    order: 6,
    xpReward: 100,
  },
  {
    id: "experience-7",
    worldId: "experience-citadel",
    name: "Conversation Catalyst",
    objective: "Discuss experiences and comparisons",
    dynamic: "Dialogue Battle",
    difficulty: 3,
    order: 7,
    xpReward: 100,
  },
  {
    id: "experience-8",
    worldId: "experience-citadel",
    name: "Listening Lighthouse",
    objective: "Understand complex narratives",
    dynamic: "Listening Expedition",
    difficulty: 3,
    order: 8,
    xpReward: 125,
  },
  {
    id: "experience-9",
    worldId: "experience-citadel",
    name: "Hispanophone Hurdle",
    objective: "Navigate B1-level transfer issues",
    dynamic: "Memory Challenge",
    difficulty: 3,
    order: 9,
    xpReward: 100,
  },
  {
    id: "experience-10",
    worldId: "experience-citadel",
    name: "Sage of Experiences",
    objective: "BOSS BATTLE - B1 Threshold Challenge",
    dynamic: "Boss Battle",
    difficulty: 3,
    order: 10,
    xpReward: 400,
  },

  // Mastery Kingdom (B2) - 10 missions
  {
    id: "mastery-1",
    worldId: "mastery-kingdom",
    name: "Passive Power",
    objective: "Transform active to passive voice",
    dynamic: "Quiz Master",
    difficulty: 4,
    order: 1,
    xpReward: 125,
  },
  {
    id: "mastery-2",
    worldId: "mastery-kingdom",
    name: "Conditional Cosmos",
    objective: "Master mixed and third conditional",
    dynamic: "Puzzle Solver",
    difficulty: 4,
    order: 2,
    xpReward: 125,
  },
  {
    id: "mastery-3",
    worldId: "mastery-kingdom",
    name: "Continuous Quest",
    objective: "Use Present Perfect Continuous correctly",
    dynamic: "Simulation Quest",
    difficulty: 4,
    order: 3,
    xpReward: 125,
  },
  {
    id: "mastery-4",
    worldId: "mastery-kingdom",
    name: "Academic Arsenal",
    objective: "Write formal academic structures",
    dynamic: "Writing Fortress",
    difficulty: 4,
    order: 4,
    xpReward: 125,
  },
  {
    id: "mastery-5",
    worldId: "mastery-kingdom",
    name: "Intonation Instructor",
    objective: "Master intonation patterns for meaning",
    dynamic: "Pronunciation Duel",
    difficulty: 4,
    order: 5,
    xpReward: 150,
  },
  {
    id: "mastery-6",
    worldId: "mastery-kingdom",
    name: "Passive Narrative",
    objective: "Tell stories using passive voice",
    dynamic: "Logic Labyrinth",
    difficulty: 4,
    order: 6,
    xpReward: 125,
  },
  {
    id: "mastery-7",
    worldId: "mastery-kingdom",
    name: "Professional Dialogue",
    objective: "Engage in formal conversations",
    dynamic: "Dialogue Battle",
    difficulty: 4,
    order: 7,
    xpReward: 125,
  },
  {
    id: "mastery-8",
    worldId: "mastery-kingdom",
    name: "Listening Labyrinth",
    objective: "Understand academic and formal speech",
    dynamic: "Listening Expedition",
    difficulty: 4,
    order: 8,
    xpReward: 150,
  },
  {
    id: "mastery-9",
    worldId: "mastery-kingdom",
    name: "Sophistication Solver",
    objective: "Combine advanced structures seamlessly",
    dynamic: "Memory Challenge",
    difficulty: 4,
    order: 9,
    xpReward: 125,
  },
  {
    id: "mastery-10",
    worldId: "mastery-kingdom",
    name: "Master of Mastery",
    objective: "BOSS BATTLE - B2 Professional Challenge",
    dynamic: "Boss Battle",
    difficulty: 4,
    order: 10,
    xpReward: 500,
  },

  // Eloquence Observatory (C1) - 10 missions
  {
    id: "eloquence-1",
    worldId: "eloquence-observatory",
    name: "Inversion Illuminator",
    objective: "Master inversion after negative adverbials",
    dynamic: "Quiz Master",
    difficulty: 5,
    order: 1,
    xpReward: 150,
  },
  {
    id: "eloquence-2",
    worldId: "eloquence-observatory",
    name: "Cleft Sentence Sculptor",
    objective: "Use cleft sentences for emphasis",
    dynamic: "Puzzle Solver",
    difficulty: 5,
    order: 2,
    xpReward: 150,
  },
  {
    id: "eloquence-3",
    worldId: "eloquence-observatory",
    name: "Rhetorical Resonance",
    objective: "Apply rhetorical devices effectively",
    dynamic: "Simulation Quest",
    difficulty: 5,
    order: 3,
    xpReward: 150,
  },
  {
    id: "eloquence-4",
    worldId: "eloquence-observatory",
    name: "Register Adjuster",
    objective: "Shift register based on context",
    dynamic: "Logic Labyrinth",
    difficulty: 5,
    order: 4,
    xpReward: 150,
  },
  {
    id: "eloquence-5",
    worldId: "eloquence-observatory",
    name: "Eloquent Expression",
    objective: "Write with sophisticated style",
    dynamic: "Writing Fortress",
    difficulty: 5,
    order: 5,
    xpReward: 150,
  },
  {
    id: "eloquence-6",
    worldId: "eloquence-observatory",
    name: "Nuanced Narrator",
    objective: "Tell stories with advanced emphasis",
    dynamic: "Dialogue Battle",
    difficulty: 5,
    order: 6,
    xpReward: 150,
  },
  {
    id: "eloquence-7",
    worldId: "eloquence-observatory",
    name: "Listening to Subtlety",
    objective: "Understand rhetorical emphasis in speech",
    dynamic: "Listening Expedition",
    difficulty: 5,
    order: 7,
    xpReward: 175,
  },
  {
    id: "eloquence-8",
    worldId: "eloquence-observatory",
    name: "Pronunciation Perfection",
    objective: "Master native-like prosody",
    dynamic: "Pronunciation Duel",
    difficulty: 5,
    order: 8,
    xpReward: 175,
  },
  {
    id: "eloquence-9",
    worldId: "eloquence-observatory",
    name: "Complex Clause Composer",
    objective: "Combine multiple advanced structures",
    dynamic: "Memory Challenge",
    difficulty: 5,
    order: 9,
    xpReward: 150,
  },
  {
    id: "eloquence-10",
    worldId: "eloquence-observatory",
    name: "Oracle of Eloquence",
    objective: "BOSS BATTLE - C1 Mastery Challenge",
    dynamic: "Boss Battle",
    difficulty: 5,
    order: 10,
    xpReward: 600,
  },

  // Perfection Sanctum (C2) - 10 missions
  {
    id: "perfection-1",
    worldId: "perfection-sanctum",
    name: "Subjunctive Sanctuary",
    objective: "Master subjunctive mood usage",
    dynamic: "Quiz Master",
    difficulty: 6,
    order: 1,
    xpReward: 175,
  },
  {
    id: "perfection-2",
    worldId: "perfection-sanctum",
    name: "Nuance Navigator",
    objective: "Understand subtle linguistic distinctions",
    dynamic: "Puzzle Solver",
    difficulty: 6,
    order: 2,
    xpReward: 175,
  },
  {
    id: "perfection-3",
    worldId: "perfection-sanctum",
    name: "Irony & Sarcasm Sage",
    objective: "Use irony and sarcasm appropriately",
    dynamic: "Simulation Quest",
    difficulty: 6,
    order: 3,
    xpReward: 175,
  },
  {
    id: "perfection-4",
    worldId: "perfection-sanctum",
    name: "Cultural Compass",
    objective: "Navigate cultural references and idioms",
    dynamic: "Logic Labyrinth",
    difficulty: 6,
    order: 4,
    xpReward: 175,
  },
  {
    id: "perfection-5",
    worldId: "perfection-sanctum",
    name: "Style Sculptor",
    objective: "Craft language with artistic precision",
    dynamic: "Writing Fortress",
    difficulty: 6,
    order: 5,
    xpReward: 175,
  },
  {
    id: "perfection-6",
    worldId: "perfection-sanctum",
    name: "Register Mastery",
    objective: "Adjust tone across all contexts",
    dynamic: "Dialogue Battle",
    difficulty: 6,
    order: 6,
    xpReward: 175,
  },
  {
    id: "perfection-7",
    worldId: "perfection-sanctum",
    name: "Listening to Nuance",
    objective: "Detect subtle meanings and tone",
    dynamic: "Listening Expedition",
    difficulty: 6,
    order: 7,
    xpReward: 200,
  },
  {
    id: "perfection-8",
    worldId: "perfection-sanctum",
    name: "Pronunciation Poetry",
    objective: "Achieve complete native fluency",
    dynamic: "Pronunciation Duel",
    difficulty: 6,
    order: 8,
    xpReward: 200,
  },
  {
    id: "perfection-9",
    worldId: "perfection-sanctum",
    name: "Idiomatic Interpreter",
    objective: "Master idiomatic expressions and slang",
    dynamic: "Memory Challenge",
    difficulty: 6,
    order: 9,
    xpReward: 175,
  },
  {
    id: "perfection-10",
    worldId: "perfection-sanctum",
    name: "Guardian of Perfection",
    objective: "BOSS BATTLE - C2 Ultimate Challenge",
    dynamic: "Boss Battle",
    difficulty: 6,
    order: 10,
    xpReward: 700,
  },

  // Pronunciation Theater (Transversal A1-C2) - 10 missions
  {
    id: "pronunciation-1",
    worldId: "pronunciation-theater",
    name: "Phoneme Fundamentals",
    objective: "Master individual phonemes (A1-A2)",
    dynamic: "Pronunciation Duel",
    difficulty: 1,
    order: 1,
    xpReward: 75,
  },
  {
    id: "pronunciation-2",
    worldId: "pronunciation-theater",
    name: "Consonant Cluster Challenge",
    objective: "Conquer consonant clusters",
    dynamic: "Puzzle Solver",
    difficulty: 2,
    order: 2,
    xpReward: 100,
  },
  {
    id: "pronunciation-3",
    worldId: "pronunciation-theater",
    name: "Vowel Vault",
    objective: "Master vowel sounds and diphthongs",
    dynamic: "Memory Challenge",
    difficulty: 2,
    order: 3,
    xpReward: 100,
  },
  {
    id: "pronunciation-4",
    worldId: "pronunciation-theater",
    name: "Stress & Rhythm Revelation",
    objective: "Learn word stress patterns",
    dynamic: "Logic Labyrinth",
    difficulty: 3,
    order: 4,
    xpReward: 125,
  },
  {
    id: "pronunciation-5",
    worldId: "pronunciation-theater",
    name: "Schwa Sanctuary",
    objective: "Master the schwa sound (/ə/)",
    dynamic: "Pronunciation Duel",
    difficulty: 3,
    order: 5,
    xpReward: 125,
  },
  {
    id: "pronunciation-6",
    worldId: "pronunciation-theater",
    name: "Intonation Instruction",
    objective: "Master sentence intonation",
    dynamic: "Simulation Quest",
    difficulty: 4,
    order: 6,
    xpReward: 150,
  },
  {
    id: "pronunciation-7",
    worldId: "pronunciation-theater",
    name: "Connected Speech",
    objective: "Understand linking and reduction",
    dynamic: "Listening Expedition",
    difficulty: 4,
    order: 7,
    xpReward: 150,
  },
  {
    id: "pronunciation-8",
    worldId: "pronunciation-theater",
    name: "Accent Adaptation",
    objective: "Achieve native-like accent",
    dynamic: "Pronunciation Duel",
    difficulty: 5,
    order: 8,
    xpReward: 175,
  },
  {
    id: "pronunciation-9",
    worldId: "pronunciation-theater",
    name: "Prosody Perfection",
    objective: "Master complete prosodic patterns",
    dynamic: "Writing Fortress",
    difficulty: 5,
    order: 9,
    xpReward: 175,
  },
  {
    id: "pronunciation-10",
    worldId: "pronunciation-theater",
    name: "Voice of the Native",
    objective: "BOSS BATTLE - Complete Pronunciation Mastery",
    dynamic: "Boss Battle",
    difficulty: 5,
    order: 10,
    xpReward: 600,
  },

  // Competence Nexus (Transversal A1-C2) - 10 missions
  {
    id: "competence-1",
    worldId: "competence-nexus",
    name: "Integrated Skills Initiate",
    objective: "Combine listening, speaking, reading, writing",
    dynamic: "Simulation Quest",
    difficulty: 3,
    order: 1,
    xpReward: 150,
  },
  {
    id: "competence-2",
    worldId: "competence-nexus",
    name: "Real-World Scenario A1",
    objective: "Navigate A1-level real situations",
    dynamic: "Dialogue Battle",
    difficulty: 1,
    order: 2,
    xpReward: 75,
  },
  {
    id: "competence-3",
    worldId: "competence-nexus",
    name: "Real-World Scenario A2",
    objective: "Handle A2-level practical tasks",
    dynamic: "Dialogue Battle",
    difficulty: 2,
    order: 3,
    xpReward: 100,
  },
  {
    id: "competence-4",
    worldId: "competence-nexus",
    name: "Real-World Scenario B1",
    objective: "Manage B1-level social interactions",
    dynamic: "Dialogue Battle",
    difficulty: 3,
    order: 4,
    xpReward: 125,
  },
  {
    id: "competence-5",
    worldId: "competence-nexus",
    name: "Real-World Scenario B2",
    objective: "Navigate B2-level professional contexts",
    dynamic: "Dialogue Battle",
    difficulty: 4,
    order: 5,
    xpReward: 150,
  },
  {
    id: "competence-6",
    worldId: "competence-nexus",
    name: "Real-World Scenario C1",
    objective: "Handle C1-level complex situations",
    dynamic: "Dialogue Battle",
    difficulty: 5,
    order: 6,
    xpReward: 175,
  },
  {
    id: "competence-7",
    worldId: "competence-nexus",
    name: "Cultural Competence Quest",
    objective: "Understand cultural nuances",
    dynamic: "Simulation Quest",
    difficulty: 4,
    order: 7,
    xpReward: 150,
  },
  {
    id: "competence-8",
    worldId: "competence-nexus",
    name: "CEFR Alignment Challenge",
    objective: "Demonstrate CEFR-aligned competence",
    dynamic: "Quiz Master",
    difficulty: 4,
    order: 8,
    xpReward: 150,
  },
  {
    id: "competence-9",
    worldId: "competence-nexus",
    name: "Practical Communication Pro",
    objective: "Apply language to real-world goals",
    dynamic: "Writing Fortress",
    difficulty: 5,
    order: 9,
    xpReward: 175,
  },
  {
    id: "competence-10",
    worldId: "competence-nexus",
    name: "Master of All Realms",
    objective: "BOSS BATTLE - Ultimate Competence Challenge",
    dynamic: "Boss Battle",
    difficulty: 6,
    order: 10,
    xpReward: 800,
  },
];

export function getWorldById(id: string): World | undefined {
  return WORLDS.find((w) => w.id === id);
}

export function getMissionsByWorldId(worldId: string): Mission[] {
  return MISSIONS.filter((m) => m.worldId === worldId).sort((a, b) => a.order - b.order);
}

export function getMissionById(id: string): Mission | undefined {
  return MISSIONS.find((m) => m.id === id);
}
